version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env.local
    environment:
      SERVER_PORT: 8080
      SERVER_BASE_URL: http://localhost:8080
      MONGODB_URI: mongodb://mongo:27017
    depends_on:
      - mongo
    networks:
      - url-shortener-network

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - url-shortener-network

volumes:
  mongo-data:

networks:
  url-shortener-network:
    driver: bridge
