# suppress inspection "UnusedProperty" for whole file
# suppress inspection "SpellCheckingInspection" for whole file
# Local Development Configuration
server.port=8080
app.base-url=http://localhost:8080

# JWT Configuration
jwt.secret=mySecretKey123456789012345678901234567890
jwt.accessTokenExpiration=3600000
jwt.refreshTokenExpiration=604800000

# MongoDB Configuration
spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27018}
spring.mongodb.database=urlshortener
app.auth.email-verification.enabled=false