package com.zufar.urlshortener.auth.dto

const val FIRST_NAME_MUST_NOT_BE_EMPTY = "First name must not be empty"
const val FIRST_NAME_IS_TOO_LONG = "First name is too long"
const val FIRST_NAME_CONTAINS_INVALID_CHARACTERS = "First name contains invalid characters"
const val LAST_NAME_MUST_NOT_BE_EMPTY = "Last name must not be empty"
const val LAST_NAME_IS_TOO_LONG = "Last name is too long"
const val LAST_NAME_CONTAINS_INVALID_CHARACTERS = "Last name contains invalid characters"
const val COUNTRY_MUST_NOT_BE_EMPTY = "Country name must not be empty"
const val COUNTRY_NAME_IS_TOO_LONG = "Country name is too long"
const val COUNTRY_NAME_CONTAINS_INVALID_CHARACTERS = "Country name contains invalid characters"
const val AGE_MUST_BE_BETWEEN_13_AND_120 = "Age must be between 13 and 120"

const val EMAIL_MUST_NOT_BE_EMPTY = "Email must not be empty"
const val EMAIL_FORMAT_IS_INVALID = "Email format is invalid"
const val EMAIL_IS_TOO_LONG = "Email is too long"

const val PASSWORD_MUST_NOT_BE_EMPTY = "Password must not be empty"
const val PASSWORD_MUST_NOT_CONTAIN_SPACES = "Password must not contain spaces"
const val PASSWORD_MUST_BE_AT_LEAST_8_CHARACTERS_LONG = "Password must be at least 8 characters long"
const val PASSWORD_IS_TOO_LONG = "Password is too long"
const val PASSWORD_MUST_CONTAIN_AT_LEAST_ONE_UPPERCASE_LETTER = "Password must contain at least one uppercase letter"
const val PASSWORD_MUST_CONTAIN_AT_LEAST_ONE_LOWERCASE_LETTER = "Password must contain at least one lowercase letter"
const val PASSWORD_MUST_CONTAIN_AT_LEAST_ONE_DIGIT = "Password must contain at least one digit"
const val PASSWORD_MUST_CONTAIN_AT_LEAST_ONE_SPECIAL_CHARACTER = "Password must contain at least one special character"